package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"log"

	"github.com/google/uuid"
	"github.com/toshim45/demo-apollo-fed-gqlgen/product/graph/model"
)

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id uuid.UUID) (model.Product, error) {
	log.Println("[FindProductByID]", id)
	return FindByID(ctx, id), nil
}

// FindTenantByID is the resolver for the findTenantByID field.
func (r *entityResolver) FindTenantByID(ctx context.Context, id uuid.UUID) (model.Tenant, error) {
	log.Println("[FindTenantByID]", id)
	return model.Tenant{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
